### ISSUE TITLE
Persistent command queue

### ISSUE THREAD

**Issue by maximilianmetti** [navoshta/MetalRenderCamera#1]
Thanks for posting this project; I found it very helpful along with [your tutorial](http://navoshta.com/metal-camera-part-1-camera-session/).

I did have a question about the way you use the command queue.  Looking over Apple's publication regarding Metal best practices, command queues are heavy to create and should be persistent ([see here](https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/PersistentObjects.html#//apple_ref/doc/uid/TP40016642-CH4-SW1)).  In this project:
https://github.com/navoshta/MetalRenderCamera/blob/master/MetalRenderCamera/MTKViewController.swift#L155
I noticed that a new command queue is created whenever you make a new command buffer.  Is there a particular reason you have for taking this approach?

**Comment by navoshta** [comment]
Sorry @maximilianmetti, I didn't keep an eye on this repo for a while! 

That's a very good point  — thanks, I've updated the code.
