### ISSUE TITLE
support yCbCr

### ISSUE THREAD

**Issue by kingslay** [navoshta/MetalRenderCamera#3]
new is only support rgb, can you support yCbCr?

**Comment by navoshta** [comment]
Sorry for not being active on this repo @kingslay — I haven't touched it in a while, but if you would like to submit a PR that would be of huge help.

**Comment by charlieforward9** [comment]
@kingslay did you ever figure out how to support yCbCr here? I am getting a red tinted view.

**Comment by kingslay** [comment]
> @kingslay did you ever figure out how to support yCbCr here? I am getting a red tinted view.

我自己搞了一个项目https://github.com/kingslay/KSPlayer 。 在我的项目里面有实现了yCbCr

**Comment by charlieforward9** [comment]
@kingslay I am unable to find the camera on this app..?

**Comment by kingslay** [comment]
是的，我的这个项目只是支持了播放这块的逻辑。录制这块没有实现
